# Generated by Django 5.2.4 on 2025-07-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralocation',
            name='approved',
            field=models.BooleanField(default=False, help_text='Moderator approval required.'),
        ),
    ]
